apiVersion: gateway.networking.k8s.io/v1
kind: BackendTLSPolicy
metadata:
  name: argo-reencrypt
  namespace: argocd
spec:
  targetRefs:
    - kind: Service
      name: argocd-server
      group: ""
  validation:
    wellKnownCACertificates: "System"
    hostname: argocd-server.argocd.svc.cluster.local