apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  annotations:
    external-dns.alpha.kubernetes.io/hostname: argo.br0.no
  name: argo-route
  namespace: argocd
spec:
  hostnames:
  - argo.br0.no
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: prod-web-gateway
    namespace: default
  rules:
  - backendRefs:
    - group: ""
      kind: Service
      name: argocd-server
      port: 80
      weight: 1
    matches:
    - path:
        type: PathPrefix
        value: /
